var annotated_dup =
[
    [ "AudioParam", "structAudioParam.html", null ],
    [ "AudioParamReq", "structAudioParamReq.html", null ],
    [ "Bitset", "structBitset.html", "structBitset" ],
    [ "BitsetItr", "structBitsetItr.html", "structBitsetItr" ],
    [ "Blind", "structBlind.html", null ],
    [ "Button", "structButton.html", "structButton" ],
    [ "Card", "structCard.html", null ],
    [ "CardObject", "structCardObject.html", null ],
    [ "ContainedHandTypes", "structContainedHandTypes.html", null ],
    [ "GameVariables", "structGameVariables.html", null ],
    [ "Hand", "structHand.html", null ],
    [ "HandValues", "structHandValues.html", null ],
    [ "Joker", "structJoker.html", null ],
    [ "JokerEffect", "structJokerEffect.html", null ],
    [ "JokerInfo", "structJokerInfo.html", null ],
    [ "JokerObject", "structJokerObject.html", null ],
    [ "JokerObjectSaveData", "structJokerObjectSaveData.html", null ],
    [ "List", "structList.html", "structList" ],
    [ "ListItr", "structListItr.html", "structListItr" ],
    [ "ListNode", "structListNode.html", "structListNode" ],
    [ "MusicPlayerState", "structMusicPlayerState.html", null ],
    [ "NinePatchRect", "structNinePatchRect.html", null ],
    [ "RngInfo", "structRngInfo.html", "structRngInfo" ],
    [ "SaveGame", "structSaveGame.html", null ],
    [ "SaveHeader", "structSaveHeader.html", null ],
    [ "SaveOptions", "structSaveOptions.html", null ],
    [ "SelectionGrid", "structSelectionGrid.html", null ],
    [ "SelectionGridRow", "structSelectionGridRow.html", null ],
    [ "SelGridRowAttributes", "structSelGridRowAttributes.html", "structSelGridRowAttributes" ],
    [ "Sprite", "structSprite.html", "structSprite" ],
    [ "SpriteObject", "structSpriteObject.html", "structSpriteObject" ],
    [ "StateInfo", "structStateInfo.html", null ],
    [ "StateMachine", "structStateMachine.html", "structStateMachine" ]
];